SHIPROCKET_API_BASE_URL = "https://apiv2.shiprocket.in/v1/external"


def get_order_creation_payload(
	shipment_name,
	pickup_date,
	delivery_company_name,
	delivery_contact,
	delivery_address,
	pickup_contact,
	mentiond_pickup_address,
	shipment_parcel,
	description_of_content,
	value_of_goods,
	service_info,
	total_weight,
):
	parcels = [
		{
			"length": parcel["length"],
			"breadth": parcel["width"],
			"height": parcel["height"],
			"weight": parcel["weight"],
			"units": parcel["count"],
		}
		for parcel in shipment_parcel
	]

	return {
		"order_id": shipment_name,
		"order_date": pickup_date,
		"channel_id": "",
		"comment": "",
		"reseller_name": "",
		"company_name": delivery_company_name,
		"billing_customer_name": delivery_contact["first_name"],
		"billing_last_name": delivery_contact["last_name"],
		"billing_address": delivery_address["address_line1"],
		"billing_address_2": delivery_address["address_line2"],
		"billing_isd_code": "",
		"billing_city": delivery_address["city"],
		"billing_pincode": delivery_address["pincode"],
		"billing_state": "Tamil Nadu",
		"billing_country": delivery_address["country"],
		"billing_email": delivery_contact["email_id"],
		"billing_phone": delivery_contact["phone"],
		"billing_alternate_phone": "",
		"shipping_is_billing": True,
		"shipping_customer_name": pickup_contact["first_name"],
		"shipping_last_name": pickup_contact["last_name"],
		"shipping_address": mentiond_pickup_address["address"],
		"shipping_address_2": mentiond_pickup_address["address_2"],
		"shipping_city": mentiond_pickup_address["city"],
		"shipping_pincode": mentiond_pickup_address["pin_code"],
		"shipping_country": mentiond_pickup_address["country"],
		"shipping_state": mentiond_pickup_address["state"],
		"shipping_email": pickup_contact["email_id"],
		"shipping_phone": pickup_contact["phone"],
		"order_items": [
			{
				"name": description_of_content,
				"sku": "N/A",
				"units": sum(parcel["count"] for parcel in shipment_parcel),
				"selling_price": value_of_goods,
				"discount": "",
				"tax": "",
				"hsn": "",
			}
		],
		"payment_method": "cod",
		"shipping_charges": service_info["total_price"],
		"giftwrap_charges": "",
		"transaction_charges": "",
		"total_discount": "",
		"sub_total": int(value_of_goods) * sum(parcel["count"] for parcel in shipment_parcel),
		"length": parcels[0]["length"],
		"breadth": parcels[0]["breadth"],
		"height": parcels[0]["height"],
		"weight": total_weight,
		"ewaybill_no": "",
		"customer_gstin": "",
		"invoice_number": "",
		"order_type": "",
		"pickup_location": mentiond_pickup_address["pickup_location"],
		"courier_company_id": service_info["carrier"],
	}
