import { realpathSync } from "node:fs";
import { createRequire } from "node:module";

// pre-commit installs ESLint dependencies next to the ESLint binary, not in the repo.
const eslintRequire = createRequire(realpathSync(process.argv[1]));

const js = (await import(eslintRequire.resolve("@eslint/js"))).default;
const globals = (await import(eslintRequire.resolve("globals"))).default;

export default [
	js.configs.recommended,
	{
		languageOptions: {
			ecmaVersion: 2022,
			sourceType: "module",
			globals: {
				...globals.browser,
				...globals.node,
				frappe: "readonly",
				erpnext: "readonly",
				Vue: "readonly",
				__: "readonly",
				repl: "readonly",
				Class: "readonly",
				locals: "readonly",
				cint: "readonly",
				cstr: "readonly",
				cur_frm: "readonly",
				cur_dialog: "readonly",
				cur_page: "readonly",
				cur_list: "readonly",
				cur_tree: "readonly",
				msg_dialog: "readonly",
				is_null: "readonly",
				in_list: "readonly",
				has_common: "readonly",
				has_words: "readonly",
				validate_email: "readonly",
				validate_name: "readonly",
				validate_phone: "readonly",
				validate_url: "readonly",
				get_number_format: "readonly",
				format_number: "readonly",
				format_currency: "readonly",
				comment_when: "readonly",
				open_url_post: "readonly",
				toTitle: "readonly",
				lstrip: "readonly",
				rstrip: "readonly",
				strip: "readonly",
				strip_html: "readonly",
				replace_all: "readonly",
				flt: "readonly",
				precision: "readonly",
				CREATE: "readonly",
				AMEND: "readonly",
				CANCEL: "readonly",
				copy_dict: "readonly",
				get_number_format_info: "readonly",
				strip_number_groups: "readonly",
				print_table: "readonly",
				Layout: "readonly",
				web_form_settings: "readonly",
				$c: "readonly",
				$a: "readonly",
				$i: "readonly",
				$bg: "readonly",
				$y: "readonly",
				$c_obj: "readonly",
				refresh_many: "readonly",
				refresh_field: "readonly",
				toggle_field: "readonly",
				get_field_obj: "readonly",
				get_query_params: "readonly",
				unhide_field: "readonly",
				hide_field: "readonly",
				set_field_options: "readonly",
				getCookie: "readonly",
				getCookies: "readonly",
				get_url_arg: "readonly",
				md5: "readonly",
				$: "readonly",
				jQuery: "readonly",
				moment: "readonly",
				hljs: "readonly",
				Awesomplete: "readonly",
				Sortable: "readonly",
				Showdown: "readonly",
				Taggle: "readonly",
				Gantt: "readonly",
				Slick: "readonly",
				Webcam: "readonly",
				PhotoSwipe: "readonly",
				PhotoSwipeUI_Default: "readonly",
				io: "readonly",
				JsBarcode: "readonly",
				L: "readonly",
				Chart: "readonly",
				DataTable: "readonly",
				Cypress: "readonly",
				cy: "readonly",
				it: "readonly",
				describe: "readonly",
				expect: "readonly",
				context: "readonly",
				before: "readonly",
				beforeEach: "readonly",
				after: "readonly",
				qz: "readonly",
				localforage: "readonly",
				extend_cscript: "readonly",
			},
		},
		rules: {
			"no-useless-escape": "off",
			camelcase: "off",
			"no-unused-vars": "off",
			"no-console": "warn",
			"no-extra-boolean-cast": "off",
			"no-control-regex": "off",
		},
	},
];
