[project]
name = "erpnext_shipping"
authors = [
    { name = "Frappe Technologies Pvt Ltd and contributors", email = "developers@frappe.io"}
]
description = "Shipping Integrations for ERPNext"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = []

[tool.bench.frappe-dependencies]
frappe = ">=15.0.0,<16.0.0"
erpnext = ">=15.0.0,<16.0.0"

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.ruff]
line-length = 110
target-version = "py310"

[tool.ruff.format]
indent-style = "tab"
docstring-code-format = true
