state_codes = {
	"tamilnadu": "TN",
	"andhrapradesh": "AP",
	"arunachalpradesh": "AR",
	"assam": "AS",
	"bihar": "BR",
	"chhattisgarh": "CG",
	"goa": "GA",
	"gujarat": "GJ",
	"haryana": "HR",
	"himachalpradesh": "HP",
	"jharkhand": "JH",
	"karnataka": "KA",
	"kerala": "KL",
	"madhyapradesh": "MP",
	"maharashtra": "MH",
	"manipur": "MN",
	"meghalaya": "ML",
	"mizoram": "MZ",
	"nagaland": "NL",
	"odisha": "OD",
	"punjab": "PB",
	"rajasthan": "RJ",
	"sikkim": "SK",
	"telangana": "TG",
	"tripura": "TR",
	"uttarpradesh": "UP",
	"uttarakhand": "UK",
	"westbengal": "WB",
	"andamanandnicobar": "AN",
	"chandigarh": "CH",
	"dadraandnagarhaveli": "DN",
	"damananddiu": "DD",
	"lakshadweep": "LD",
	"delhi": "DL",
	"puducherry": "PY",
	"ladakh": "LA",
	"jammukashmir": "JK",
}
status_map = {
	"PRE_TRANSIT": "In Progress",
	"TRANSIT": "In Progress",
	"OUT_FOR_DELIVERY": "In Progress",
	"DELIVERED": "Delivered",
	"FAILURE": "Lost",
	"RETURNED": "Returned",
	"UNKNOWN": "In Progress",
}
